Fix static linking problem with libgcrypt
When libgcrypt is used, it is linked with libgpg-error, so we should
also test that libgpg-error is available, and include -lgpg-error in
the LIBS variable.

This fixes build issues like:

  CCLD     xml
/home/thomas/projets/buildroot/output/host/usr/bfin-buildroot-uclinux-uclibc/sysroot/usr/lib/libexslt.a(crypto.o): In function `_exsltCryptoGcryptInit':
crypto.c:(.text+0x112): undefined reference to `_gcry_check_version'
/home/thomas/projets/buildroot/output/host/usr/bfin-buildroot-uclinux-uclibc/sysroot/usr/lib/libexslt.a(crypto.o): In function `_exsltCryptoRc4DecryptFunction':
crypto.c:(.text+0x316): undefined reference to `_gcry_cipher_open'
crypto.c:(.text+0x32a): undefined reference to `_gcry_strerror'
crypto.c:(.text+0x34c): undefined reference to `_gcry_cipher_setkey'

Which are caused by the AC_SEARCH_LIBS() test for libgcrypt to fail
due to -lgpg-error not been present in the LIBS variable.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>